### PR TITLE
Dependencies issues

### PR DESCRIPTION
**Pull request by ilchemla**
1/ Add User-Agent to headers as Validator.Nu requires it now
2/ Update html5-lint package version

### CODE REVIEW

**Comment by lbeder** [comment]
👍

**Comment by cbuchert** [comment]
Who do we need to bribe to get this pull request through?

**Review by cbuchert — APPROVED** [review]

**Comment by BonnoHxC** [comment]
Doesnt work for me...I change everything of what you telling me but it is still show me the error HTML lint Api is down. Skipping linting.

**Comment by ilchemla** [comment]
@BonnoHxC 
This PR is still not merged.
Did you try to use my fork in the `package.json`?

`"gulp-html5-lint": "git+https://github.com/ilchemla/gulp-html5-lint.git#1.2.0",`

**Comment by BonnoHxC** [comment]
I show you my Plugin "gulp-html5-lint.js" and some details from package.json
I thought I changed everything you telling me but maybe you could find my mistake?


`
module.exports = function gulpHtml5Lint(options) {
    var linterOpts = _.safeMerge({
            apiCheck: {
                timeout: moment.duration(10, 'seconds').asMilliseconds(),
                triggerError: false
            }
        }, options),
        errorOutputList = [],
        req,
        apiAvailable;

    try {
        req = request('GET', linterOpts.apiCheck.website || 'https://html5.validator.nu', {
            timeout: linterOpts.apiCheck.timeout,
            headers: {
                'Content-Type': 'text/html; charset=utf-8',
                'User-Agent': 'gulp-html5-lint'
            }
        });
    }
    catch (e) {
        req = {
            statusCode: 0
        };
    }
    finally {
        apiAvailable = req.statusCode === 200;
    }

    if (!apiAvailable && !linterOpts.apiCheck.triggerError) {
        gutil.log('HTML lint API is DOWN. Skipping linting.');
    }

    function transformFunction(file, enc, cb) {
        if (file.isNull()) {
            return cb(null, file);
        }

        if (!apiAvailable) {
            if (linterOpts.apiCheck.triggerError) {
                return cb(new PluginError(pluginName, 'HTML lint API is down. Aborting.'));
            }
            return cb(null, file);
        }

        if (file.isStream()) {
            return cb(new PluginError(pluginName, 'Streaming not supported'));
        }

        try {
            htmlLint(file.contents.toString(), linterOpts, function htmlLintCallback(err, results) {
                _.forEach(results.messages, function(msg) {
                    var errorMsg = msg.type + ': ' + msg.message + '\n' +
                        '    at ' + file.path + ':' + msg.lastLine + ':' + msg.lastColumn;

                    errorOutputList.push(errorMsg);
                });

                cb(null, file);
            });
        } catch (err) {
            errorOutputList.push(err.toString());
            cb(null, file);
        }
    }

    function flushFunction(cb) {
        if (!_.isEmpty(errorOutputList)) {
            /*jshint validthis:true */
            this.emit('error', new PluginError(pluginName, '\n' + errorOutputList.join('\n\n') + '\n', {
                showStack: false
            }));
        }
        cb();
    }

    return through.obj(transformFunction, flushFunction);
};

`

  "dependencies": {
    "gulp-util": "^3.0.4",
    "html5-lint": "^0.3.0",
    "ls-lodash": "^2.2.2",
    "moment": "^2.10.6",
    "sync-request": "^3.0.1",
    "through2": "^2.0.3"
  },
  "description": "gulp plugin for html5-lint",
  "devDependencies": {
    "chai": "^3.5.0",
    "chai-as-promised": "^6.0.0",
    "event-stream": "^3.3.0",
    "gulp": "^3.8.11",
    "lvsf-gulp-tasks": "^1.1.0",
    "sinon": "^1.17.2",
    "sinon-chai": "^2.7.0"
  },
  "directories": {},
  "dist": {
    "shasum": "3d3002720225b727aa23f72fa9e6a8ee16b745dc",
    "tarball": "https://registry.npmjs.org/gulp-html5-lint/-/gulp-html5-lint-1.1.0.tgz"
  },
  "gitHead": "c4cf004ba9155173e6f4e5e7ea208a9b9b7816ea",
  "homepage": "https://github.com/LiveSafe/gulp-html5-lint",
  "keywords": [
    "gulp",
    "html",
    "html5",
    "lint",
    "gulpplugin"
  ],
  "license": "MIT",
  "main": "lib/gulp-html5-lint.js",
  "maintainers": [
    {
      "name": "spaintrain",
      "email": "mc.s.pain.how.er+npm@gmail.com"
    }
  ],
  "name": "gulp-html5-lint",
  "optionalDependencies": {},
  "readme": "ERROR: No README data found!",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/ilchemla/gulp-html5-lint.git#1.2.0"
  },
  "scripts": {
    "release": "./do-release.sh",
    "test": "gulp test"
  },
  "version": "1.1.0"
}

**Comment by SalomonSmeke** [comment]
Using @ilchemla 's fork, the plugin works great. Please merge this.

**Comment by SalomonSmeke** [comment]
Thanks

**Comment by ilchemla** [comment]
Thank you!

**Comment by cbuchert** [comment]
Bless you, my son.

**Pull request merged**
